services:
  db:
    container_name: AtendeBot_DataBase
    image: postgres:16
    env_file:
      - ./db/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - banco-data:/var/lib/postgresql/data 
  backend:
    container_name: AtendeBot_Backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db 
  
  frontend:
    container_name: AtendeBot_Frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    restart: always
  
volumes:
  banco-data: 